//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.RelMembresiaCliente = new HashSet<RelMembresiaCliente>();
        }
    
        public int IdCliente { get; set; }
        public int IdGimnasio { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public bool Activo { get; set; }
    
        public virtual Gimnasio Gimnasio { get; set; }
        public virtual ICollection<RelMembresiaCliente> RelMembresiaCliente { get; set; }
    }
}
