//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Horario = new HashSet<Horario>();
            this.RelEntrenadorCurso = new HashSet<RelEntrenadorCurso>();
            this.RelMembresiaCurso = new HashSet<RelMembresiaCurso>();
        }
    
        public int IdCurso { get; set; }
        public int IdGimnasio { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
    
        public virtual Gimnasio Gimnasio { get; set; }
        public virtual ICollection<Horario> Horario { get; set; }
        public virtual ICollection<RelEntrenadorCurso> RelEntrenadorCurso { get; set; }
        public virtual ICollection<RelMembresiaCurso> RelMembresiaCurso { get; set; }
    }
}
