//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gimnasio
    {
        public Gimnasio()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Curso = new HashSet<Curso>();
            this.Entrenador = new HashSet<Entrenador>();
            this.Inventario = new HashSet<Inventario>();
            this.Membresia = new HashSet<Membresia>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IdGimnasio { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Curso> Curso { get; set; }
        public virtual ICollection<Entrenador> Entrenador { get; set; }
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual ICollection<Membresia> Membresia { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
