//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gymware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int IdInventario { get; set; }
        public int IdGimnasio { get; set; }
        public int IdMaterial { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Gimnasio Gimnasio { get; set; }
        public virtual Material Material { get; set; }
    }
}
