
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Gymware.Models
{

using System;
    using System.Collections.Generic;
    using System.Linq;
    
public partial class Usuario
{

    public Usuario()
    {

        this.RelacionUsuarioVenta = new HashSet<RelacionUsuarioVenta>();

        this.UsuarioCheckLog = new HashSet<UsuarioCheckLog>();

    }


    public int IdUsuario { get; set; }

    public int IdGimnasio { get; set; }

    public int IdEntrenador { get; set; }

    public string Nombre { get; set; }

    public string NombreUsuario { get; set; }

    public string Contraseña { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    public bool Activo { get; set; }

    public static bool Login(string User, string pass)
        {
            bool b = false;
            try
            {
                using (var entities = new GimnasioEntities())
                {
                    b = entities.Usuario.Any(x => x.NombreUsuario == User && x.Contraseña == pass);
                }
            }

            catch (Exception e)
            {
                throw e;
            }
            return b;
        }

    public virtual Entrenador Entrenador { get; set; }

    public virtual Gimnasio Gimnasio { get; set; }

    public virtual ICollection<RelacionUsuarioVenta> RelacionUsuarioVenta { get; set; }

    public virtual ICollection<UsuarioCheckLog> UsuarioCheckLog { get; set; }

}

}
